# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-18 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_auto_20181118_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todolisttwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
