# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0004_auto_20181119_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todolisttwo',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
